[tool.poetry]
name = "example"
version = "0.1.0"
description = "Example"
authors = ["Stéphane Brunner <stephane.brunner@camptocamp.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"

[build-system]
requires = ["poetry-core==1.0.7"]
build-backend = "poetry.core.masonry.api"
